# NASA Near Earth Orbit Analysis

## 1. Extract
Connect to the NASA API and pull the raw JSON.

In [78]:
#Import libraries 
import os
import requests
import pandas as pd
from dotenv import load_dotenv

# Load environment variables from the root .env file
load_dotenv(dotenv_path="../.env") 

# Retrieve NASA api key
API_KEY = os.getenv("NASA_API_KEY")

# Build api url with the api key
# Build your URL using the environment variable
START_DATE = "2026-07-10"
END_DATE = "2026-07-17"
URL= f'https://api.nasa.gov/neo/rest/v1/feed?start_date={START_DATE}&end_date={END_DATE}&api_key={API_KEY}'

# Test the connection & fetch data
response = requests.get(URL)
raw_data = response.json()
print(f"Total elements returned: {raw_data['element_count']}")
print(f"Response Status: {response.status_code}")

Total elements returned: 35
Response Status: 200

## 2. Transform

Clean the data with pandas, handle missing values, convert types, engineer useful features.

In [76]:
# Hold our flattened records
asteroid_list = []

# Loop through each date in the feed
neo_dates = raw_data['near_earth_objects']
for date in neo_dates:
    for asteroid in neo_dates[date]:
        
        # Extract close approach details
        close_approach = asteroid['close_approach_data'][0] if asteroid['close_approach_data'] else {}
        
        # Build a flat dictionary for each specific record
        asteroid_record = {
            'asteroid_id': asteroid['id'],
            'name': asteroid['name'],
            'absolute_magnitude_h': float(asteroid['absolute_magnitude_h']),
            'estimated_diameter_max_km': float(asteroid['estimated_diameter']['kilometers']['estimated_diameter_max']),
            'is_potentially_hazardous': bool(asteroid['is_potentially_hazardous_asteroid']),
            
            # Event specific details converted to floats from strings
            'close_approach_date': close_approach.get('close_approach_date'),
            'relative_velocity_kph': float(close_approach.get('relative_velocity', {}).get('kilometers_per_hour', 0)),
            'miss_distance_km': float(close_approach.get('miss_distance', {}).get('kilometers', 0)),
            'orbiting_body': close_approach.get('orbiting_body')
        }
        
        asteroid_list.append(asteroid_record)

df = pd.DataFrame(asteroid_list)

## 3. Explore

Inspect the JSON structure and identify the fields we need.

In [71]:
# Check total rows
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   asteroid_id                35 non-null     object
 1   name                       35 non-null     object
 2   absolute_magnitude_h       35 non-null     float64
 3   estimated_diameter_max_km  35 non-null     float64
 4   is_potentially_hazardous   35 non-null     bool
 5   close_approach_date        35 non-null     object
 6   relative_velocity_kph      35 non-null     float64
 7   miss_distance_km           35 non-null     float64
 8   orbiting_body              35 non-null     object
dtypes: bool(1), float64(4), object(4)
memory usage: 2.3+ KB
None

In [61]:
# Summary statistics for numeric columns (speed, diameter, miss distance)
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
absolute_magnitude_h,35.0,2.359400e+01,2.700324e+00,1.814000e+01,2.131500e+01,2.396000e+01,2.529000e+01,2.860000e+01
estimated_diameter_max_km,35.0,2.253861e-01,2.853989e-01,1.132505e-02,5.204906e-02,9.594890e-02,3.245148e-01,1.399716e+00
relative_velocity_kph,35.0,5.099541e+04,2.685581e+04,1.604265e+04,2.946850e+04,4.617646e+04,6.481601e+04,1.228172e+05
miss_distance_km,35.0,4.086651e+07,1.929192e+07,6.832281e+06,2.626541e+07,3.744177e+07,5.734524e+07,7.087333e+07

In [72]:
# Check for null values
df.isnull().sum()

asteroid_id                  0
name                         0
absolute_magnitude_h         0
estimated_diameter_max_km    0
is_potentially_hazardous     0
close_approach_date          0
relative_velocity_kph        0
miss_distance_km             0
orbiting_body                0
dtype: int64

In [63]:
# Count hazardous vs non hazardous asteroids
print(df['is_potentially_hazardous'].value_counts())
print(df['is_potentially_hazardous'].value_counts(normalize=True) * 100)

is_potentially_hazardous
False    29
True      6
Name: count, dtype: int64
is_potentially_hazardous
False    82.857143
True     17.142857
Name: proportion, dtype: float64

In [43]:
# Top 3 closest approaches to Earth
df.sort_values(by='miss_distance_km').head(3)[['name', 'close_approach_date', 'miss_distance_km', 'is_potentially_hazardous']]

,name,close_approach_date,miss_distance_km,is_potentially_hazardous
15,(2007 AA2),2026-07-11,6.832281e+06,False
28,(2016 NB1),2026-07-14,1.159381e+07,False
10,(2013 AS27),2026-07-10,1.269313e+07,True

In [44]:
# Top 3 fastest moving asteroids
df.sort_values(by='relative_velocity_kph', ascending=False).head(3)[['name', 'relative_velocity_kph', 'estimated_diameter_max_km']]

                 name  relative_velocity_kph  estimated_diameter_max_km
1         (2009 HA21)          122817.185453                   0.401828
8   452639 (2005 UY6)          111834.764284                   1.399716
32         (2010 WB3)           98978.803376                   0.608191

In [48]:
# Compare average size of hazardous vs non-hazardous asteroids
df.groupby('is_potentially_hazardous')['estimated_diameter_max_km'].agg(['count', 'mean', 'max', 'min'])

                          count      mean       max       min
is_potentially_hazardous
False                        29  0.176862  1.399716  0.011325
True                          6  0.459917  0.871044  0.314804

In [73]:
# Check if any asteroid ID appears more than once
df['asteroid_id'].value_counts().max() > 1

np.False_

In [77]:
# Save the cleaned DataFrame to a CSV file
df.to_csv('../data/processed/nasa_clean.csv', index=False)

## 4. Load to PostgreSQL

Export the cleaned dataset and import it into PostgreSQL.

In [80]:
# postgresql toolkit
import psycopg2
from sqlalchemy import create_engine

load_dotenv(dotenv_path="../.env")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")

engine = create_engine(f'postgresql+psycopg2://postgres:{POSTGRES_PASSWORD}@localhost/nasa_neo_db')

try: 
    engine
    print("Connection to PostgreSQL database successful")
except Exception as e:
    print("Error connecting to PostgreSQL database:")

Connection to PostgreSQL database successful

In [82]:
df.to_sql('near_earth_objects', con=engine, if_exists='replace', index=False)

35

## 5. Tableau Dashboard

Build an interactive Tableau dashboard to visualize Near Earth Object metrics, proximity rankings, and approach timelines.

🔗 **[View Interactive Dashboard on Tableau Public](https://public.tableau.com/shared/PCPRX6SNN?:display_count=n&:origin=viz_share_link)**

![NASA NEO Tracker Dashboard](../tableau/tableau-1.png)
![NASA NEO Tracker Dashboard](../tableau/tabeau-2.png)